dataset:
  name: "co3d_duster"
  train_bs: 1
  num_viewpoints: 2
  num_ref: 1
  target_idx: 1
  train_width: 512
  train_height: 512
  meta_paths:
    - "./data/fashion_meta.json"
  # Margin of frame indexes between ref and tgt images
  sample_margin: 30  

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'no'
  enable_xformers_memory_efficient_attention: true
  gradient_checkpointing: False
  max_train_steps: 2000000
  max_grad_norm: 1.0
  
  # lr
  learning_rate: 1.0e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 2000

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

vae_model_path: /mnt/data1/minseop/multiview-gen/checkpoints/sd-vae-ft-mse
image_encoder_path: 'laion/CLIP-ViT-H-14-laion2B-s32B-b79K'
model_path: "/mnt/data1/minseop/multiview-gen/checkpoints/moai-singleview-only-pointmap"

model_path_scratch: ""

feature_fusion_type: "attention_full_sharing"
train_vggt: true
normalized_pose: true
view_range: 10
sampling_views: 15

debugging: true
local_data: true
realestate_only: false
step_control: false
inference: true
inference_run_name: "MoAI_real_extrapolate"
infer_setting: "realestate_eval" # "realestate_eval" "co3d_eval" "view_search" "like_training" "revisit"
revisit_dir: "/mnt/data2/minseop/eval_results/Nova/05_23_00_41_01/5be4f1f46b408d68_idx_133_160_66_80_50"
save_everything: true
visualize_attention: false
view_select: false
my_select: false
recurrent: false

re10k_eval_setting: "extrapolate"
re10k_view_exp: true
re10k_eval_viewpoint: 2

nomesh_normal: false

interpolate_only: false
optimizer_load: true
train_from_scratch: false
train_from_complete: true

img_weight: 1.0
weight_1: 3.0
weight_2: 10.0
weight_3: 0.7

train_geo_only: false
train_geo_2_only: false
geo_first: true
geo_second: false
geo_third: false
use_geo_ref_unet: true
use_geo_2_ref_unet: false
use_warped_geo_cond_at_geo: false
geo_setting: "pointmap"
geo_setting_2: "depth"
# depth_min: 0.05
# depth_max: 0.8897
depth_min: 0.5185
depth_max: 2.2866

use_mesh: false
downsample: false
use_normal: false
use_normal_mask: false
downsample_by: 2

use_depthmap: false
use_conf: false
use_plucker: false
use_warped_img_cond: false
gt_cor_reg: false
use_gt_cor: false
pure_gt: false
gt_mask_threshold: 0.004
conditioning_pointmap_norm: true
embed_pointmap_norm: true

switcher: false
multitask_mode: "loc" 
multitask_weighting: false
image_weight: 0.9
ref_net_expand: false
both_loss: false
uncertainty_loss: false
multitask: false

point_masking: false
masking_percent: 0.9

find_unused_params: false
use_lora: false
weight_dtype: 'fp32'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True 
pose_guider_pretrain: False

seed: 12580
resume_from_checkpoint: ""
# resume_from_checkpoint: ""
checkpointing_steps: 1000
save_model_epoch_interval: 5
exp_name: 'inference'
output_dir: './exp_output' 

compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 0,1,2,3,4,5,6,7
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 8
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 29400